### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by sguinetti**
Thank you for providing this application. I hope this contribution will help a lot when implementing the Spanish translation.

### CODE REVIEW

**Comment by flxholle** [comment]
Nice, Thank you very much.

**Comment by flxholle** [comment]
Hi @sguinetti 
Could you please translate the files short_description.txt and full_description.txt, too:
https://github.com/asdoi/TimeTable/tree/master/fastlane/metadata/android/en-US

These files are the app the description for F-Droid and (in future) for Play Store.
If you are not used to fastlane file structure, you can just publish the translation here and I will create the necessary files.
Thank you in advance

**Comment by sguinetti** [comment]
I understand, I'll take a look. Its structure is kind of easy, I just need to copy and paste it into ES. I'll see if I can get it.

**Comment by sguinetti** [comment]
It's complete. #2

**Pull request merged**
